### Get all movies
GET http://localhost:1234/movies

### Get a movie by ID
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Get a movie by genre
GET http://localhost:1234/movies?genre=Action

### Create a movie with POST
POST http://localhost:1234/movies
Content-Type: application/json

{
  "title": "The Godfather",
  "year": 1975,
  "director": "Francis Ford Coppola",
  "duration": "175",
  "poster": "https://i.etsystatic.com/35681979/r/il/dfe3ba/3957859451/il_fullxfull.3957859451_h27r.jpg",
  "genre": [
    "Crime",
    "Drama"
  ]
}